### ISSUE TITLE
需要支持 range 级别的 bug fix

### ISSUE THREAD

**Issue by fengmk2** [cnpm/bug-versions#200]
https://github.com/npm/cli/security/advisories/GHSA-hj9c-8jmm-8c52?utm_campaign=Adventures%20in%20Nodeland&utm_medium=email&utm_source=Revue%20newsletter

**Comment by fengmk2** [comment]
先 hotfix node 版本 https://github.com/cnpm/bug-versions/pull/201

**Comment by laibao101** [comment]
现在支持 range 的 bug version 了吗
