### ISSUE TITLE
request  2.84.0 & 2.84.1

### ISSUE THREAD

**Issue by demohi** [cnpm/bug-versions#3]
request 刚刚发布的版本 2.84.x  依赖了 hawk 7.x     hawk 7.x  依赖 node v8，导致在非 node v8环境下出现错误。

**Comment by marcccc** [comment]
同样遇到这个问题，拜托尽快修复下~

**Comment by imsobear** [comment]
https://github.com/request/request/issues/2891

**Comment by popomore** [comment]
为啥不提 PR

**Comment by popomore** [comment]
https://github.com/request/request/issues/2891
