### ISSUE TITLE
tslib 1.12.0 breaks a lot packages

### ISSUE THREAD

**Issue by Icemic** [cnpm/bug-versions#92]
tslib 发了一个 breaking change 导致了问题，目前已知 typeorm 已经不可用

https://github.com/typeorm/typeorm/issues/6054
https://github.com/microsoft/tslib/issues/103

**Comment by linxiaowu66** [comment]
any updates? @gxcsoccer

**Comment by Icemic** [comment]
Closed. Out of date since [tslib problem has been solved at v1.13.0](https://github.com/microsoft/tslib/issues/103#issuecomment-628297050).
